mount e "%1"
SET PATH=M:\COMPILE;%PATH%
SET PATH=E:\MASM611\BIN;E:\MASM611\BINR;%PATH%
SET LIB=E:\MASM611\LIB
SET INCLUDE=E:\MASM611\INCLUDE
SET INIT=E:\MASM611\INIT
SET HELPFILES=E:\MASM611\HELP\*.HLP
SET TMP=E:\MASM611\TMP
xplx /D %2
masm /ICOMPILE %2
link /E /F /PACKCODE /SE:10240 %2+COMPILE\NATIVEX,%2.exe,,,nul.def
exit /b
