#!/bin/sh

name_to_step() {
    local name="$1"
    while [[ "$name" != "${name%_*}" ]]; do
        name="${name%_*}"
    done
    echo "$name"
}

step=$(name_to_step ${STEP:-stepA_mal})

TERM=xterm dosemu -dumb "${step^^}.EXE"
